# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerSensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.IntegerField(default=0)),
                ('inner_temp', models.FloatField(default=0)),
                ('inner_humidity', models.FloatField(default=0)),
                ('co2', models.FloatField(default=0)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='InnerSensorfileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OutSensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.IntegerField(default=0)),
                ('wind_direct', models.FloatField(default=0)),
                ('wind_velocity', models.FloatField(default=0)),
                ('rain', models.FloatField(default=0)),
                ('solar', models.FloatField(default=0)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='OutSensorfileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StandardDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_len_min', models.FloatField(default=0)),
                ('plant_len_optimal', models.FloatField(default=0)),
                ('plant_len_max', models.FloatField(default=0)),
                ('stem_min', models.FloatField(default=0)),
                ('stem_optimal', models.FloatField(default=0)),
                ('stem_max', models.FloatField(default=0)),
                ('leaf_len_min', models.FloatField(default=0)),
                ('leaf_len_optimal', models.FloatField(default=0)),
                ('leaf_len_max', models.FloatField(default=0)),
                ('leaf_width_min', models.FloatField(default=0)),
                ('leaf_width_optimal', models.FloatField(default=0)),
                ('leaf_width_max', models.FloatField(default=0)),
                ('leaf_n_min', models.FloatField(default=0)),
                ('leaf_n_optimal', models.FloatField(default=0)),
                ('leaf_n_max', models.FloatField(default=0)),
                ('joint_interval_min', models.FloatField(default=0)),
                ('joint_interval_optimal', models.FloatField(default=0)),
                ('joint_interval_max', models.FloatField(default=0)),
                ('fcluster_interval_min', models.FloatField(default=0)),
                ('fcluster_interval_optimal', models.FloatField(default=0)),
                ('fcluster_interval_max', models.FloatField(default=0)),
                ('fcluster_n', models.IntegerField(default=0)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='StandardfileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='DataFile',
            new_name='BaseDataFile',
        ),
        migrations.RenameModel(
            old_name='fileUpload',
            new_name='BasefileUpload',
        ),
    ]
