# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20171222_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddatafile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
