# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_investigationdata_investigationfileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationdata',
            name='day',
        ),
        migrations.AddField(
            model_name='investigationdata',
            name='week',
            field=models.TextField(default=0),
        ),
    ]
