# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20171228_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddatafile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
