# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_investigationdata_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationdata',
            name='farm',
            field=models.TextField(default=''),
        ),
    ]
